/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-30 06:09:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/C:/workspace44/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/library/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/admin/../include/header1.jsp", Long.valueOf(1693201543291L));
    _jspx_dependants.put("/admin/../include/header2.jsp", Long.valueOf(1693201543293L));
    _jspx_dependants.put("/admin/../include/footer.jsp", Long.valueOf(1693201543289L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1689126080262L));
    _jspx_dependants.put("/admin/../include/newaside.jsp", Long.valueOf(1693201543299L));
    _jspx_dependants.put("/admin/../include/nav2.jsp", Long.valueOf(1693285535003L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>관리자화면</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/lib.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".wrapper {\r\n");
      out.write("    margin: 0px auto;\r\n");
      out.write("    width: 1200px;\r\n");
      out.write("    height:1000px;\r\n");
      out.write("    position: relative; \r\n");
      out.write("    border:1px solid black;\r\n");
      out.write("}\r\n");
      out.write("#chapter_1 , #chapter_2{\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    width: 98%;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    border: 1px solid #e9e9e9;\r\n");
      out.write("    background: #f7f7f7;\r\n");
      out.write("}\r\n");
      out.write("textarea , h1,h2,h3{\r\n");
      out.write("    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("}\r\n");
      out.write("fieldset {\r\n");
      out.write("	border:0;\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<header class=\"header1\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@200&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function fn_logout() {\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : \"POST\",\r\n");
      out.write("		data : \"\", //  전송되는 데이터 값은 없다.\r\n");
      out.write("		url : \"/libLogout.do\", \r\n");
      out.write("		\r\n");
      out.write("		datatype : \"text\",\r\n");
      out.write("		success 	 : function(data) {\r\n");
      out.write("			 if(data == \"1\") {\r\n");
      out.write("					alert(\"로그아웃 되었습니다.\");\r\n");
      out.write("					location = \"/\"; // 메인화면으로 이동\r\n");
      out.write("				 }\r\n");
      out.write("			 },\r\n");
      out.write("			error 		 : 	function() {\r\n");
      out.write("				 alert(\"전송실패\");\r\n");
      out.write("			 }\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"libtop\" >\r\n");
      out.write("<a href=\"/\">홈으로</a> | \r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div> ");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<header class=\"header2\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"libtitle\" >\r\n");
      out.write("<a href=\"/\">하이도서관</a>\r\n");
      out.write("&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"searchFrm\" method=\"post\" action=\"/bookRent.do\" style=\"display: inline;\">\r\n");
      out.write("  <input type=\"hidden\" name=\"searchCondition\" id=\"searchCondition\" value=\"title\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"input-container\">\r\n");
      out.write("    <div class=\"icon-container\">\r\n");
      out.write("      <img src=\"../icon/inputsearch.gif\" class=\"input-icon\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <input type=\"text\" id=\"searchKeyword\" name=\"searchKeyword\" class=\"search\" onfocus=\"clearIcon()\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <input type=\"submit\" id=\"search\" name=\"search\" class=\"button\" style=\"position: relative; bottom: 9px;\" value=\"검색\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("	    <a href=\"/\"><img src=\"../icon/main.gif\" alt=\"search 아이콘\" class=\"mainicon\" style=\"vertical-align: middle;\"></a>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	<nav class=\"nav2\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("  <table class=\"menu-btn2\" style=\"width:1200px; align:center;\">\r\n");
      out.write("    	<colgroup>\r\n");
      out.write("			<col width=\"22%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"18%\"/>\r\n");
      out.write("		</colgroup>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td><a href=\"#\"></a></td>\r\n");
      out.write("      <td><a href=\"/bookInput.do\">도서관리</a></td>\r\n");
      out.write("      <td><a href=\"/libAdminReserve.do\">열람실관리</a></td>\r\n");
      out.write("      <td><a href=\"/libNoticeList.do\">공지관리</a></td>\r\n");
      out.write("      <td><a href=\"#\">회원관리</a></td>\r\n");
      out.write("      <td><a href=\"#\"></a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  <ul class=\"menu-list2\">\r\n");
      out.write("   		<table width=\"1200px;\" style=\"font-size:20px;\">\r\n");
      out.write("   		<colgroup>\r\n");
      out.write("			<col width=\"22%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"18%\"/>\r\n");
      out.write("		</colgroup>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/bookInput.do\">도서등록</a></td>\r\n");
      out.write("				<td><a href=\"/libAdminReserve.do\">사용현황</a></td>\r\n");
      out.write("				<td><a href=\"/libNoticeList.do\">공지사항관리</a></td>\r\n");
      out.write("				<td><a href=\"/libAdminMemberList.do\">회원관리</a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/bookReturn.do\">대여/반납 관리</a></td>\r\n");
      out.write("				<td><a href=\"/libAdminArchive.do\">사용기록</a></td>\r\n");
      out.write("				<td><a href=\"/libEventList.do\">문화행사관리</a></td>\r\n");
      out.write("				<td><a href=\"/libAdminMemberList2.do\">탈퇴회원관리</a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/listModify.do\">보유리스트</a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/adminCalendar.do\">일정관리</a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			\r\n");
      out.write("		</table>\r\n");
      out.write("  </ul>");
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	\r\n");
      out.write("	<section class=\"section1\">\r\n");
      out.write("		<div class=\"sec1\">\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"flex-item\">\r\n");
      out.write("			<div class=\"container\" style=\"border:0px solid black;\" >\r\n");
      out.write("				     \r\n");
      out.write("				     <!-- 본문 입력 -->\r\n");
      out.write("		\r\n");
      out.write("    \r\n");
      out.write("            		<!--  본문 입력 -->\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("			");
      out.write("\r\n");
      out.write("남양주시평생학습원사업자번호 : 132-83-05566대표자 : 이순덕<br>\r\n");
      out.write("주소 : 경기도 남양주시 다산중앙로82번안길 138(다산동 정약용도서관)<br>\r\n");
      out.write("진건도서관경기도 남양주시 진건읍 진건오남로 41-25TEL : 031-590-8260<br>\r\n");
      out.write("Copyright © 남양주시평생학습원. ALL RIGHTS RESERVED.<br>");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("	<aside class=\"new-aside\">\r\n");
      out.write("	 ");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("<script>\r\n");
      out.write("window.onload = function() {\r\n");
      out.write("  showScrollTopImage();\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("window.onscroll = function() {\r\n");
      out.write("  showScrollTopImage();\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("var scrollTimeout;\r\n");
      out.write("\r\n");
      out.write("function showScrollTopImage() {\r\n");
      out.write("  clearTimeout(scrollTimeout);\r\n");
      out.write("  var scrollImg = document.querySelector(\".scroll-top-img\");\r\n");
      out.write("  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {\r\n");
      out.write("    scrollImg.classList.add(\"visible\");\r\n");
      out.write("  } else {\r\n");
      out.write("    scrollTimeout = setTimeout(function() {\r\n");
      out.write("      scrollImg.classList.remove(\"visible\");\r\n");
      out.write("    }, 300);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function scrollToTop() {\r\n");
      out.write("  document.body.scrollTop = 0;\r\n");
      out.write("  document.documentElement.scrollTop = 0;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 이미지를 클릭하여 위로 이동하는 링크 -->\r\n");
      out.write("<a href=\"javascript:void(0);\" onclick=\"scrollToTop()\" class=\"scroll-top-img\">\r\n");
      out.write("  <img src=\"../icon/up.gif\" alt=\"up 아이콘\" class=\"icon\"><br>\r\n");
      out.write("  위로가기\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</aside>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /admin/../include/header1.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("s_userid");
      // /admin/../include/header1.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/admin/../include/header1.jsp(5,0) '${sessionScope.SessionUserID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionUserID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /admin/../include/header1.jsp(37,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<a href=\"/libConditions.do\">회원가입</a> |\r\n");
          out.write("	<a href=\"/libLoginWrite.do\"><b>로그인</b></a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /admin/../include/header1.jsp(41,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != null && s_userid != 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<a href=\"/libMemberDetail.do\">내 정보</a> |\r\n");
          out.write("	<a href=\"javascript:fn_logout()\"><b>로그아웃</b></a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /admin/../include/header1.jsp(45,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<a href=\"/adminMain.do\" style=\"color: red; font-weight: bold;\">관리자모드</a> |\r\n");
          out.write("	<a href=\"javascript:fn_logout()\"><b>로그아웃</b></a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
