/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-28 06:11:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class libConditions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/member/../include/libCondition1.jsp", Long.valueOf(1693201543295L));
    _jspx_dependants.put("/member/../include/header1.jsp", Long.valueOf(1693201543291L));
    _jspx_dependants.put("/member/../include/aside6.jsp", Long.valueOf(1693201543287L));
    _jspx_dependants.put("jar:file:/C:/workspace44/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/library/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/member/../include/header2.jsp", Long.valueOf(1693201543293L));
    _jspx_dependants.put("/member/../include/nav.jsp", Long.valueOf(1693201543277L));
    _jspx_dependants.put("/member/../include/libCondition2.jsp", Long.valueOf(1693201543297L));
    _jspx_dependants.put("/member/../include/footer.jsp", Long.valueOf(1693201543289L));
    _jspx_dependants.put("/member/../include/newaside.jsp", Long.valueOf(1693201543299L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1689126080262L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>이용약관</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/lib.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//모두 동의 체크박스 처리 기능\r\n");
      out.write("$(function(){\r\n");
      out.write("	$(\"#agree_all\").click(function(){\r\n");
      out.write("		var len = $(\"input[name='agree']\").length;\r\n");
      out.write("    	var bool = true;\r\n");
      out.write("    	if( $(\"#agree_all\").is(\":checked\") == false ) bool = false;\r\n");
      out.write("     	for(var i=0; i<len; i++) {\r\n");
      out.write(" 			$(\"input[name='agree']\")[i].checked = bool;\r\n");
      out.write(" 		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$(\"#button1\").click(function(){\r\n");
      out.write("		var len = $(\"input[name='agree']\").length;\r\n");
      out.write("		var bool = true;\r\n");
      out.write("		\r\n");
      out.write("		for(var i=0; i<len; i++) {\r\n");
      out.write("			if($(\"input[name='agree']\")[i].checked == false) {            \r\n");
      out.write("				bool = false;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		if(bool == false) {\r\n");
      out.write("			alert(\"약관에 모두 동의해주세요.\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		location=\"/libJoinWrite.do\";\r\n");
      out.write("	});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".wrapper {\r\n");
      out.write("    margin: 0px auto;\r\n");
      out.write("    width: 1200px;\r\n");
      out.write("    height:1000px;\r\n");
      out.write("    position: relative; \r\n");
      out.write("    border:1px solid black;\r\n");
      out.write("}\r\n");
      out.write(".chapter {\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    padding: 5px;\r\n");
      out.write("    width: 98%;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("    border: 1px solid #e9e9e9;\r\n");
      out.write("    background: white;\r\n");
      out.write("    resize: none;\r\n");
      out.write("}\r\n");
      out.write(".chapter::-webkit-scrollbar {\r\n");
      out.write("    width: 10px;\r\n");
      out.write("}\r\n");
      out.write(".chapter::-webkit-scrollbar-thumb {\r\n");
      out.write("    background-color: #2f3542;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    background-clip: padding-box;\r\n");
      out.write("    border: 2px solid transparent;\r\n");
      out.write("}\r\n");
      out.write(".chapter::-webkit-scrollbar-track {\r\n");
      out.write("    background-color: grey;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: inset 0px 0px 5px white;\r\n");
      out.write("}\r\n");
      out.write("textarea , h1,h2,h3{\r\n");
      out.write("    font-family: 'Nanum Gothic', sans-serif;\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("}\r\n");
      out.write("fieldset {\r\n");
      out.write("	border:0;\r\n");
      out.write("}	\r\n");
      out.write(".btn_submit {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    font-size: 1em;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"header1\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@200&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function fn_logout() {\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : \"POST\",\r\n");
      out.write("		data : \"\", //  전송되는 데이터 값은 없다.\r\n");
      out.write("		url : \"/libLogout.do\", \r\n");
      out.write("		\r\n");
      out.write("		datatype : \"text\",\r\n");
      out.write("		success 	 : function(data) {\r\n");
      out.write("			 if(data == \"1\") {\r\n");
      out.write("					alert(\"로그아웃 되었습니다.\");\r\n");
      out.write("					location = \"/\"; // 메인화면으로 이동\r\n");
      out.write("				 }\r\n");
      out.write("			 },\r\n");
      out.write("			error 		 : 	function() {\r\n");
      out.write("				 alert(\"전송실패\");\r\n");
      out.write("			 }\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"libtop\" >\r\n");
      out.write("<a href=\"/\">홈으로</a> | \r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div> ");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("    <header class=\"header2\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"libtitle\" >\r\n");
      out.write("<a href=\"/\">하이도서관</a>\r\n");
      out.write("&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"searchFrm\" method=\"post\" action=\"/bookRent.do\" style=\"display: inline;\">\r\n");
      out.write("  <input type=\"hidden\" name=\"searchCondition\" id=\"searchCondition\" value=\"title\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"input-container\">\r\n");
      out.write("    <div class=\"icon-container\">\r\n");
      out.write("      <img src=\"../icon/inputsearch.gif\" class=\"input-icon\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <input type=\"text\" id=\"searchKeyword\" name=\"searchKeyword\" class=\"search\" onfocus=\"clearIcon()\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <input type=\"submit\" id=\"search\" name=\"search\" class=\"button\" style=\"position: relative; bottom: 9px;\" value=\"검색\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("	    <a href=\"/\"><img src=\"../icon/main.gif\" alt=\"search 아이콘\" class=\"mainicon\" style=\"vertical-align: middle;\"></a>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"nav\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  <table class=\"menu-btn\" style=\"width:1200px; align:center;\">\r\n");
      out.write("   		<colgroup>\r\n");
      out.write("			<col width=\"12%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"13%\"/>\r\n");
      out.write("		</colgroup>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td><a href=\"#\"></a></td>\r\n");
      out.write("      <td><a href=\"/guide.do\">이용안내</a></td>\r\n");
      out.write("      <td><a href=\"/bookSearch.do\">자료검색</a></td>\r\n");
      out.write("      <td><a href=\"/libNoticeList2.do\">도서관소식</a></td>\r\n");
      out.write("      <td><a href=\"/libReserve.do\">신청서비스</a></td>\r\n");
      out.write("      <td>\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </td>\r\n");
      out.write("      <td><a href=\"#\"></a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  <ul class=\"menu-list\">\r\n");
      out.write("   		<table width=\"1200px;\" style=\"font-size:20px;\">\r\n");
      out.write("	   		<colgroup>\r\n");
      out.write("				<col width=\"12%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"13%\"/>\r\n");
      out.write("			</colgroup>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/libMap.do\">오시는길</a></td>\r\n");
      out.write("				<td><a href=\"/bookSearch.do\">통합검색</a></td>\r\n");
      out.write("				<td><a href=\"/libNoticeList2.do\">공지사항</a></td>\r\n");
      out.write("				<td><a href=\"/libReserve.do\">열람실</a></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			    ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/guide.do\">이용시간</a></td>\r\n");
      out.write("				<td><a href=\"/bookRent.do\">대여하기</a></td>\r\n");
      out.write("				<td><a href=\"/libEventList2.do\">문화행사</a></td>\r\n");
      out.write("				\r\n");
      out.write("				<td><a href=\"/voluntary.do\">자원봉사신청</a></td>\r\n");
      out.write("				<td><a href=\"/libArchive.do?session_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">열람실기록</a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/reserveGuide.do\">열람실이용</a></td>\r\n");
      out.write("				<td><a href=\"/newBook.do\">신착도서</a></td>\r\n");
      out.write("				<td><a href=\"/libCalendar.do\">일정</a></td>\r\n");
      out.write("				<td><a href=\"/tourGuide.do\">도서견학신청</a></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/rentGuide.do\">대출/반납</a></td>\r\n");
      out.write("				<td><a href=\"/popularBook.do\">인기도서</a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("  </ul>");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section1\">\r\n");
      out.write("        <div class=\"sec1\">\r\n");
      out.write("            <aside class=\"aside\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("		<table style=\"border-collapse: collapse;width:220px;\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td style=\"font-size:35px;height:180px; background-size: cover;\">\r\n");
      out.write("				<a href=\"/libConditions.do\">회원가입</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"80\"><a href=\"/libLoginWrite.do\">로그인</a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"80\"><a href=\"/libFindUserId.do\">아이디찾기</a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"80\"><a href=\"/libFindUserPass.do\">비밀번호찾기</a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"80\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>");
      out.write("\r\n");
      out.write("            </aside>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"flex-item\">\r\n");
      out.write("                <div class=\"container\" style=\"border:0px solid black;\">\r\n");
      out.write("                    <!-- 본문 입력 -->\r\n");
      out.write("                    <div style=\"margin-bottom: 50px; font-size: 1.3em; font-weight: bold;\">\r\n");
      out.write("                        회원가입\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <section style=\"margin: 0 0 20px; padding: 20px 0;\">\r\n");
      out.write("                        <h2 style=\"font-size: 1em; margin: 0 0 20px; text-align: center;\">이용약관</h2>\r\n");
      out.write("                        <textarea readonly class=\"chapter\">\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("제1장 총칙\r\n");
      out.write("제1조 목적\r\n");
      out.write("이 약관은 남양주도서관(이하 \"도서관\"이라 한다) 홈페이지가 제공하는 모든 서비스(이하 \"서비스\"라 한다)의 이용조건 및 절차에 관한 사항을 규정함을 목적으로 합니다.\r\n");
      out.write("\r\n");
      out.write("제2조 정의\r\n");
      out.write("이용자 : 서비스에 접속하여 남양주도서관이 제공하는 서비스를 이용하는 회원 및 비회원\r\n");
      out.write("비회원 : 회원가입하지 않고 서비스에 접속하거나 이용하는 사람\r\n");
      out.write("준회원 : 서비스에 접속하여 이 약관에 동의하고 본인인증 절차를 거친 후 아이디와 비밀번호를 발급 받은 사람\r\n");
      out.write("정회원 : 준회원 상태에서 도서관에 방문하여 회원증 발급을 받은 사람\r\n");
      out.write("이용계약 : 서비스 이용과 관련하여 도서관과 이용자간에 체결하는 계약\r\n");
      out.write("가입 : 도서관이 제공하는 신청서 양식에 해당 정보를 기입하고, 본 약관에 동의하여 서비스 이용계약을 완료시키는 행위\r\n");
      out.write("ID : 회원의 식별을 위한 고유정보로 도서관이 승인하는 문자 또는 숫자의 조합\r\n");
      out.write("비밀번호 : 회원ID로 식별되는 회원의 본인 여부를 검증하기 위하여 회원이 설정한 고유의 문자와 숫자의 조합\r\n");
      out.write("이용해지 : 준회원의 경우 홈페이지의 회원탈퇴 페이지에서 탈퇴하는 것. 정회원의 경우 홈페이지 탈퇴 후 도서관에 방문하여 오프라인 탈퇴하는 것을 의미한다.\r\n");
      out.write("제3조 효력의 발생과 변경\r\n");
      out.write("회원은 변경된 약관에 동의하지 않을 경우 회원 탈퇴(해지)를 요청할 수 있으며, 변경된 약관의 효력 발생일로부터 7일 이후에도 거부의사를 표시하지 아니하고 서비스를 계속 사용할 경우 약관의 변경 사항에 동의한 것으로 간주됩니다.\r\n");
      out.write("\r\n");
      out.write("이 약관의 내용은 도서관 홈페이지 화면에 게시하거나 기타의 방법으로 공지함으로써 효력이 발생됩니다.\r\n");
      out.write("도서관은 이 약관을 변경할 수 있으며, 변경된 약관은 이용자에게 공지함으로써 효력이 발생됩니다.\r\n");
      out.write("제4조 준용규정\r\n");
      out.write("이 약관에 명시되지 않은 사항은 전기통신기본법, 전기통신사업법 및 기타 관련법령의 규정에 따릅니다.\r\n");
      out.write("\r\n");
      out.write("제2장 서비스 이용계약\r\n");
      out.write("제5조 이용계약의 성립\r\n");
      out.write("이용계약은 이용자의 이용신청에 대한 도서관의 승낙과 이용자의 약관 내용에 대한 동의로 성립됩니다.\r\n");
      out.write("\r\n");
      out.write("제6조 이용신청\r\n");
      out.write("이용신청은 인터넷을 통하여 이용자가 도서관에서 정한 가입신청서에 기록하여 신청할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("제7조 이용신청의 승낙\r\n");
      out.write("회원이 신청서의 모든 사항을 정확히 기재하여 이용신청을 하였을 경우에 승낙합니다.\r\n");
      out.write("다음 각호의 1에 해당하는 경우에는 이용 승낙을 하지 않을 수 있습니다.\r\n");
      out.write("01. 이용신청의 내용을 허위로 기재한 경우\r\n");
      out.write("02. 다른 사람의 명의를 사용하여 신청한 경우\r\n");
      out.write("03. 기타 이용신청 요건에 미비 되었을 때\r\n");
      out.write("04. 사이트를 이용하여 법령과 본 약관이 금지하는 행위를 하는 경우");
      out.write("\r\n");
      out.write("                        </textarea>\r\n");
      out.write("                        <fieldset style=\"padding: 10px 0 0; text-align: right;\">\r\n");
      out.write("                            <label for=\"agree11\">회원가입약관의 내용에 동의합니다.</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"agree\" class=\"\">\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                    </section>\r\n");
      out.write("                    \r\n");
      out.write("                    <section style=\"margin: 0 0 20px; padding: 20px 0;\">\r\n");
      out.write("                        <h2 style=\"margin: 0 0 20px; text-align: center; font-size: 1em;\">개인정보 수집 및 이용에 대한 안내</h2>\r\n");
      out.write("                        <textarea readonly class=\"chapter\">\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("남양주도서관에서 취급하는 모든 개인정보는 관련법령에 근거하거나 정보주체의 동의에 의하여 수집·보유 및 처리되고 있습니다.\r\n");
      out.write("[개인정보 보호법]은 이러한 개인정보의 취급에 대한 일반적 규범을 제시하고 있으며, 남양주도서관에서는 이러한 법령의 규정에 따라 수집 보유 및 처리하는 개인정보를 공공업무의 적절한 수행과 국민의 권익을 보호하기 위해 적법하고 적정하게 취급할 것입니다.\r\n");
      out.write("남양주도서관에서는 [개인정보 보호법]에 따라 이용자의 개인정보보호 및 권익을 보호하고 개인정보와 관련한 이용자의 고충을 원활하게 처리할 수 있도록 다음과 같은 개인정보 처리방침을 두고 있습니다.\r\n");
      out.write("제1조 개인정보의 처리목적\r\n");
      out.write("남양주도서관은 개인정보를 다음의 목적을 위해 처리합니다. 처리한 개인정보는 다음의 목적 이외의 용도로는 이용되지 않으며, 이용 목적이 변경될 시에는 사전 동의를 받을 예정입니다.\r\n");
      out.write("\r\n");
      out.write("홈페이지 회원 가입 및 관리\r\n");
      out.write("회원가입 및 회원제 서비스 이용 및 제한적 본인 확인절차에 따른 본인확인, 개인식별, 부정이용방지, 비인가 이용방지, 가입 의사 확인, 고지사항 전달 등을 목적으로 개인정보를 처리\r\n");
      out.write("남양주도서관 홈페이지 서비스 향상 및 정책평가\r\n");
      out.write("민원처리\r\n");
      out.write("제2조 개인정보의 처리 및 보유기간\r\n");
      out.write("이용자의 개인정보는 원칙적으로 개인정보의 처리 목적이 달성되면 지체없이 파기합니다.\r\n");
      out.write("회원정보\r\n");
      out.write("보존항목 : 이름, 생년월일, 성별, 주소, 휴대폰번호, 전화번호, 개인 아이디, 비밀번호, 이메일주소, I-PIN 정보\r\n");
      out.write("보존기간 : 탈퇴 즉시 삭제\r\n");
      out.write("제3조 개인정보의 제3자 제공\r\n");
      out.write("남양주도서관은 원칙적으로 이용자의 개인정보를 제1조 (개인정보의 처리 목적)에서 명시한 범위 내에서 처리하며, 이용자의 사전 동의 없이 본래의 범위를 초과하여 처리하거나 제3자에게 제공하지 않습니다.\r\n");
      out.write("\r\n");
      out.write("다만, 다음의 경우는 예외로 처리됩니다.\r\n");
      out.write("\r\n");
      out.write("다른 법률에 특별한 규정이 있는 경우\r\n");
      out.write("범죄의 수사와 같이 개인정보 보호법 제 18조 ②에 해당되는 경우\r\n");
      out.write("이용자가 사전에 제3자 제공 및 공개에 동의한 경우\r\n");
      out.write("서비스의 제공에 관한 계약의 이행을 위하여 필요한 개인정보로서 경제적/기술적인 사유로 통상의 동의를 받는 것이 현저히 곤란한 경우\r\n");
      out.write("개인을 식별하기에 특정할 수 없는 상태로 가공하여 이용하는 경우\r\n");
      out.write("제4조 개인정보처리의 위탁\r\n");
      out.write("남양주도서관은 원활한 개인정보 업무처리를 위하여 다음과 같이 개인정보 처리업무를 위탁하고 있습니다.\r\n");
      out.write("위탁받는 자	위탁 업무	계약기간\r\n");
      out.write("㈜제이넷	도서관 홈페이지 유지보수	2020.1.1. ~ 2020.12.31.\r\n");
      out.write("㈜채움씨앤아이	도서관리시스템 유지보수	2020.1.1. ~ 2020.12.31.\r\n");
      out.write("남양주도서관은 위탁계약 체결시 『개인정보 보호법』 제26조에 따라 위탁업무 수행목적 외 개인정보 처리금지, 기술적ㆍ관리적 보호조치, 재위탁 제한, 수탁자에 대한 관리ㆍ감독, 손해배상 등 책임에 관한 사항을 계약서 등 문서에 명시하고, 수탁자가 개인정보를 안전하게 처리하는지를 감독하고 있습니다.\r\n");
      out.write("위탁업무의 내용이나 수탁자가 변경될 경우에는 지체없이 본 개인정보 처리방침을 통하여 공개하도록 하겠습니다.\r\n");
      out.write("제5조 정보주체와 법정대리인의 권리·의무 및 행사방법\r\n");
      out.write("수집방법\r\n");
      out.write("정보주체는 남양주도서관에 대해 언제든지 개인정보 열람ㆍ정정ㆍ삭제ㆍ처리정지 요구 등의 권리를 행사할 수 있습니다.\r\n");
      out.write("제1항에 따른 권리 행사는 남양주도서관에 대해 『개인정보 보호법 시행령』 제41조 제1항에 따라 서면, 전자우편, 모사전송(FAX) 등을 통하여 하실 수 있으며, 남양주도서관은 이에 대해 지체 없이 조치하겠습니다.\r\n");
      out.write("제1항에 따른 권리 행사는 정보주체의 법정대리인이나 위임을 받은 자 등 대리인을 통하여 하실 수 있습니다. 이 경우 『개인정보 보호법 시행규칙』 별지 제11호 서식에 따른 위임장을 제출하셔야 합니다.\r\n");
      out.write("개인정보 열람 및 처리정지 요구는 『개인정보 보호법』 제35조 제5항, 제37조 제2항에 의하여 정보주체의 권리가 제한 될 수 있습니다.\r\n");
      out.write("개인정보의 정정 및 삭제 요구는 다른 법령에서 그 개인정보가 수집 대상으로 명시되어 있는 경우에는 그 삭제를 요구할 수 없습니다.\r\n");
      out.write("남양주도서관은 정보주체 권리에 따른 열람의 요구, 정정·삭제의 요구, 처리정지의 요구 시 열람 등 요구를 한 자가 본인이거나 정당한 대리인인지를 확인합니다.\r\n");
      out.write("제6조 처리하는 개인정보의 항목\r\n");
      out.write("남양주도서관에서 서비스 제공 및 민원 처리를 위해 처리하는 개인정보 항목 및 수집 방법은 다음과 같습니다.\r\n");
      out.write("\r\n");
      out.write("개인정보항목\r\n");
      out.write("이름, 생년월일, 성별, 주소, 휴대폰번호, 전화번호, 개인 아이디, 비밀번호, 이메일주소, I-PIN 정보\r\n");
      out.write("수집방법\r\n");
      out.write("온라인 수집 (홈페이지 회원)\r\n");
      out.write("제7조 개인정보의 파기\r\n");
      out.write("남양주도서관은 원칙적으로 개인정보 처리목적이 달성된 경우에는 지체 없이 해당 개인정보를 파기합니다. 다만, 다른 법률에 따라 보존하여야하는 경우에는 그러하지 않습니다. 파기의 절차, 기한 및 방법은 다음과 같습니다.\r\n");
      out.write("\r\n");
      out.write("파기절차\r\n");
      out.write("이용자가 입력한 정보는 목적 달성 후 내부 방침 및 관련 법령에 따라 일정기간 저장된 후 혹은 즉시 파기됩니다.\r\n");
      out.write("파기방법\r\n");
      out.write("남양주도서관에서 처리하는 개인정보파일은 전자적 파일 형태로 기록되기 때문에 재생할 수 없는 기술적 방법을 사용하여 파기합니다.\r\n");
      out.write("제8조 개인정보의 안전성 확보조치\r\n");
      out.write("남양주도서관은 「개인정보 보호법」 제29조에 따라 다음과 같이 안전성 확보에 필요한 기술적, 관리적, 물리적 조치를 하고 있습니다.\r\n");
      out.write("\r\n");
      out.write("개인정보의 암호화\r\n");
      out.write("이용자의 개인정보는 암호화 되어 저장 및 관리되고 있습니다. 또한 중요한 데이터는 저장 및 전송 시 암호화하여 사용하는 등 별도 보안기능을 사용하고 있습니다.\r\n");
      out.write("개인정보 취급 담당자의 최소화 및 교육\r\n");
      out.write("개인정보를 취급하는 담당자를 지정하고 최소화하여 개인정보를 관리하는 대책을 시행 및 개인정보 교육을 실시하고 있습니다.\r\n");
      out.write("비인가자에 대한 출입 통제\r\n");
      out.write("개인정보를 보관하고 있는 개인정보시스템의 물리적 보관 장소를 별도로 두고 이에 대해 출입통제 절차를 수립, 운영하고 있습니다.\r\n");
      out.write("내부관리계획의 수립 및 시행\r\n");
      out.write("남양주도서관의 내부관리계획 수립 및 시행은 행정안전부의 내부관리 지침을 준수하여 시행합니다.\r\n");
      out.write("접속기록의 보관 및 위변조 방지\r\n");
      out.write("개인정보처리시스템에 접속한 기록(웹 로그, 요약정보 등)을 최소 6개월 이상 보관, 관리하고 있으며, 접속 기록이 위변조 및 도난, 분실되지 않도록 보안기능을 사용하고 있습니다.\r\n");
      out.write("개인정보에 대한 접근 제한\r\n");
      out.write("개인정보를 처리하는 데이터베이스시스템에 대한 접근권한의 부여, 변경, 말소를 통하여 개인정보에 대한 접근 통제를 위하여 필요한 조치를 하고 있으며 침입차단시스템을 이용하여 외부로부터의 무단 접근을 통제하고 있습니다.\r\n");
      out.write("해킹 등에 대비한 기술적 대책\r\n");
      out.write("남양주도서관은 해킹이나 컴퓨터 바이러스 등에 의한 개인정보 유출 및 훼손을 막기 위하여 보안프로그램을 설치하고 주기적인 갱신·점검을 하며 외부로부터 접근이 통제된 구역에 시스템을 설치하고 기술적/물리적으로 감시 및 차단하고 있습니다. 또한 네트워크 트래픽의 통제(Monitoring)는 물론 불법적으로 정보를 변경하는 등의 시도를 탐지하고 있습니다.\r\n");
      out.write("제9조 개인정보 보호책임자\r\n");
      out.write("남양주시 도서관은 개인정보 처리에 관한 업무를 총괄해서 책임지고, 개인정보 처리와 관련한 정보주체의 불만처리 및 피해구제 등을 위하여 아래와 같이 개인정보 보호책임자를 지정하고 있습니다.\r\n");
      out.write("\r\n");
      out.write("개인정보 보호책임자\r\n");
      out.write("소속 : 평생학습원\r\n");
      out.write("성명 : 조성기\r\n");
      out.write("개인정보 보호담당자\r\n");
      out.write("소속 : 도서관운영과\r\n");
      out.write("성명 : 성명준\r\n");
      out.write("전화번호 : 031-590-2874\r\n");
      out.write("제10조 개인정보 처리방침의 변경\r\n");
      out.write("이 개인정보처리방침은 게시일로부터 적용되며, 법령 및 방침에 따른 변경내용의 추가, 삭제 및 정정이 있는 경우에는 공지사항을 통하여 고지할 것입니다.\r\n");
      out.write("\r\n");
      out.write("제11조 권익침해 구제방법\r\n");
      out.write("정보주체는 개인정보침해로 인한 구제를 받기 위하여 개인정보분쟁조정위원회, 한국인터넷진흥원 개인정보침해신고센터 등에 분쟁해결이나 상담 등을 신청할 수 있습니다. 이 밖에 기타 개인정보침해의 신고, 상담에 대하여는 아래의 기관에 문의하시기 바랍니다.\r\n");
      out.write("\r\n");
      out.write("개인정보분쟁조정위원회 : (국번없이) 118(내선2번)\r\n");
      out.write("정보보호마크인증위원회 : 02-580-0533~4 (http://eprivacy.or.kr)\r\n");
      out.write("대검찰청 첨단범죄수사과 : 02-3480-2000 (http://www.spo.go.kr)\r\n");
      out.write("경찰청 사이버테러대응센터 : 1566-0112 (http://www.netan.go.kr)");
      out.write("\r\n");
      out.write("                        </textarea>\r\n");
      out.write("                        <fieldset class=\"\" style=\"padding: 10px 0 0; text-align:right;\">\r\n");
      out.write("                            <label for=\"agree21\">개인정보처리방침안내의 내용에 동의합니다.</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"agree\" id=\"agree21\" class=\"\">\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("\r\n");
      out.write("                        <fieldset class=\"\" style=\"padding: 30px 0 0; text-align: right;\">\r\n");
      out.write("                            <label for=\"agree21\">모두 동의합니다.</label>\r\n");
      out.write("                            <input type=\"checkbox\" name=\"agree_all\" id=\"agree_all\" class=\"\">\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                    </section>\r\n");
      out.write("                    \r\n");
      out.write("                    <div style=\"text-align: center;\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn_submit\" id=\"button1\" onclick=\"return false;\" value=\"회원가입\" style=\"cursor: pointer;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("남양주시평생학습원사업자번호 : 132-83-05566대표자 : 이순덕<br>\r\n");
      out.write("주소 : 경기도 남양주시 다산중앙로82번안길 138(다산동 정약용도서관)<br>\r\n");
      out.write("진건도서관경기도 남양주시 진건읍 진건오남로 41-25TEL : 031-590-8260<br>\r\n");
      out.write("Copyright © 남양주시평생학습원. ALL RIGHTS RESERVED.<br>");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    <aside class=\"new-aside\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("<script>\r\n");
      out.write("window.onload = function() {\r\n");
      out.write("  showScrollTopImage();\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("window.onscroll = function() {\r\n");
      out.write("  showScrollTopImage();\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("var scrollTimeout;\r\n");
      out.write("\r\n");
      out.write("function showScrollTopImage() {\r\n");
      out.write("  clearTimeout(scrollTimeout);\r\n");
      out.write("  var scrollImg = document.querySelector(\".scroll-top-img\");\r\n");
      out.write("  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {\r\n");
      out.write("    scrollImg.classList.add(\"visible\");\r\n");
      out.write("  } else {\r\n");
      out.write("    scrollTimeout = setTimeout(function() {\r\n");
      out.write("      scrollImg.classList.remove(\"visible\");\r\n");
      out.write("    }, 300);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function scrollToTop() {\r\n");
      out.write("  document.body.scrollTop = 0;\r\n");
      out.write("  document.documentElement.scrollTop = 0;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 이미지를 클릭하여 위로 이동하는 링크 -->\r\n");
      out.write("<a href=\"javascript:void(0);\" onclick=\"scrollToTop()\" class=\"scroll-top-img\">\r\n");
      out.write("  <img src=\"../icon/up.gif\" alt=\"up 아이콘\" class=\"icon\"><br>\r\n");
      out.write("  위로가기\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /member/../include/header1.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("s_userid");
      // /member/../include/header1.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/member/../include/header1.jsp(5,0) '${sessionScope.SessionUserID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionUserID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /member/../include/header1.jsp(37,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<a href=\"/libConditions.do\">회원가입</a> |\r\n");
          out.write("	<a href=\"/libLoginWrite.do\"><b>로그인</b></a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /member/../include/header1.jsp(41,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != null && s_userid != 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<a href=\"/libMemberDetail.do\">내 정보</a> |\r\n");
          out.write("	<a href=\"javascript:fn_logout()\"><b>로그아웃</b></a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /member/../include/header1.jsp(45,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<a href=\"/adminMain.do\" style=\"color: red; font-weight: bold;\">관리자모드</a> |\r\n");
          out.write("	<a href=\"javascript:fn_logout()\"><b>로그아웃</b></a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /member/../include/nav.jsp(4,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("session_id");
      // /member/../include/nav.jsp(4,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/member/../include/nav.jsp(4,4) '${sessionScope.SessionUserID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionUserID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /member/../include/nav.jsp(24,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      	<a href=\"/libLoginWrite.do\">나의 도서관</a> \r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /member/../include/nav.jsp(27,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      	<a href=\"/myBookList.do\">나의 도서관</a> \r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /member/../include/nav.jsp(52,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			    	<a href=\"/libLoginWrite.do\">대여목록</a> \r\n");
          out.write("			    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /member/../include/nav.jsp(55,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			    	<a href=\"/myBookList.do\">대여목록</a> \r\n");
          out.write("			    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /member/../include/nav.jsp(78,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                	<a href=\"/libMemberDetail.do\">내 정보</a>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }
}
