/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.76
 * Generated at: 2023-08-28 06:11:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class libJoinWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/member/../include/header1.jsp", Long.valueOf(1693201543291L));
    _jspx_dependants.put("/member/../include/aside6.jsp", Long.valueOf(1693201543287L));
    _jspx_dependants.put("jar:file:/C:/workspace44/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/library/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/member/../include/header2.jsp", Long.valueOf(1693201543293L));
    _jspx_dependants.put("/member/../include/nav.jsp", Long.valueOf(1693201543277L));
    _jspx_dependants.put("/member/../include/footer.jsp", Long.valueOf(1693201543289L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1689126080262L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"../include/address.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/lib.css\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	// 입력한 아이디값에 대한 체크\r\n");
      out.write("	$(\"#userid\").keyup(function(){\r\n");
      out.write("		\r\n");
      out.write("		let userid = $(\"#userid\").val();\r\n");
      out.write("		let msg = \"\";\r\n");
      out.write("		let result = 0;\r\n");
      out.write("		if(userid.length >= 4 && userid.length <= 15) {\r\n");
      out.write("			result = fn_userid(userid);\r\n");
      out.write("		}\r\n");
      out.write("		$(\"#id_usable\").val(\"N\")\r\n");
      out.write("		if(result == 0) {\r\n");
      out.write("			msg = \"<font color='red'>아이디는 4~15 자리 사이로 입력해주세요.</font>\";\r\n");
      out.write("		} else if(result == 1) {\r\n");
      out.write("			msg = \"<font color='green'>사용가능한 아이디입니다.</font>\";\r\n");
      out.write("			$(\"#id_usable\").val(\"Y\")\r\n");
      out.write("		} else if(result == 2) {\r\n");
      out.write("			msg = \"<font color='red'>이미 사용중인 아이디입니다.</font>\";\r\n");
      out.write("		} else if(result == 3) {\r\n");
      out.write("			msg = \"<font color='red'>형식에 맞지않는 아이디입니다.</font>\";\r\n");
      out.write("		}\r\n");
      out.write("		$(\"#msg_userid\").html(msg);\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	// 회원가입 버튼 클릭 시\r\n");
      out.write("	$(\"#btn_submit\").click(function(){\r\n");
      out.write("		// 정보 입력값 호출,공백처리 및 정규표현식 적용\r\n");
      out.write("		\r\n");
      out.write("		// 회원가입 정보값 호출\r\n");
      out.write("		let userid 		= $.trim($(\"#userid\").val());\r\n");
      out.write("		let userpass    = $.trim($(\"#userpass\").val());\r\n");
      out.write("		let userpass2   = $(\"#userpass2\").val();\r\n");
      out.write("		let name 	    = $.trim($(\"#name\").val());\r\n");
      out.write("		let id_usable   = $.trim($(\"#id_usable\").val());\r\n");
      out.write("		\r\n");
      out.write("		let y1 			= $(\"#y1\").val();\r\n");
      out.write("		let m2 			= $(\"#m2\").val();\r\n");
      out.write("		let d3 			= $(\"#d3\").val();\r\n");
      out.write("		let birth 		= y1+\"-\"+m2+\"-\"+d3;\r\n");
      out.write("		\r\n");
      out.write("		let p1 			= $(\"#p1\").val();\r\n");
      out.write("		let p2 			= $.trim($(\"#p2\").val());\r\n");
      out.write("		let p3 			= $.trim($(\"#p3\").val());\r\n");
      out.write("		let phone		= p1+\"-\"+p2+\"-\"+p3;\r\n");
      out.write("		\r\n");
      out.write("		let email 		= $.trim($(\"#email\").val());\r\n");
      out.write("		\r\n");
      out.write("		let addr1 		= $.trim($(\"#addr1\").val());\r\n");
      out.write("		let addr2 		= $.trim($(\"#addr2\").val());\r\n");
      out.write("		\r\n");
      out.write("		// 체크유무에 따른 데이터 베이스 저장 값 설정\r\n");
      out.write("		let mailchk = $(\"#mailchk\").prop(\"checked\") ? \"Y\" : \"N\";\r\n");
      out.write("		let smschk = $(\"#smschk\").prop(\"checked\") ? \"Y\" : \"N\";\r\n");
      out.write("		\r\n");
      out.write("		// 데이터 공백제거\r\n");
      out.write("		userid 			= userid.replace(\" \",\"\");\r\n");
      out.write("		userpass   		= userpass.replace(\" \",\"\");\r\n");
      out.write("		name  			= name.replace(\" \",\"\");\r\n");
      out.write("		p1 				= p1.replace(\" \",\"\");\r\n");
      out.write("		p2 				= p2.replace(\" \",\"\");\r\n");
      out.write("		p3 				= p3.replace(\" \",\"\");\r\n");
      out.write("		email 			= email.replace(\" \",\"\");\r\n");
      out.write("		\r\n");
      out.write("		$(\"#userid\").val(userid);\r\n");
      out.write("		$(\"#userpass\").val(userpass);\r\n");
      out.write("		$(\"#name\").val(name);\r\n");
      out.write("		$(\"#p1\").val(p1);\r\n");
      out.write("		$(\"#p2\").val(p2);\r\n");
      out.write("		$(\"#p3\").val(p3);\r\n");
      out.write("		$(\"#email\").val(email);\r\n");
      out.write("		\r\n");
      out.write("		if(name == \"\") {\r\n");
      out.write("			alert(\"이름을 입력해주세요.\");\r\n");
      out.write("			$(\"#name\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		// 이름 정규표현식 처리\r\n");
      out.write("		let name_pattern = /^[a-zA-Z가-힣]*$/;\r\n");
      out.write("	    if (!name_pattern.test(name)) {\r\n");
      out.write("	      alert(\"이름을 다시 입력해주세요.\");\r\n");
      out.write("	      $(\"#name\").focus();\r\n");
      out.write("	      return false;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    if(userid.length < 4 || userid.length > 12) {\r\n");
      out.write("			alert(\"아이디는 4~12자리 사이로 입력해주세요.\");\r\n");
      out.write("			$(\"#userid\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	    \r\n");
      out.write("		if(id_usable == \"N\") {\r\n");
      out.write("			alert(\"아이디를 다시 확인해주세요.\");\r\n");
      out.write("			$(\"#id_usable\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(userpass.length < 6 || userpass.length > 20) {\r\n");
      out.write("			alert(\"암호는 6~20자리 사이로 입력해주세요.\");\r\n");
      out.write("			$(\"#userpass\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(userpass != userpass2) {\r\n");
      out.write("			alert(\"암호가 일치하지 않습니다.\");\r\n");
      out.write("			$(\"#userpass2\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		// 비밀번호 정규표현식 처리\r\n");
      out.write("		let userpass_pattern = /^.*(?=^.{6,20}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&]).*$/;\r\n");
      out.write("	    if (!userpass_pattern.test(userpass)) {\r\n");
      out.write("	      alert(\"비밀번호가 양식에 맞지 않습니다.\\n영문대소문자, 숫자, 특수문자 중 3종류 이상의 조합으로 6~20자리로 입력해주세요.\");\r\n");
      out.write("	      $(\"#userpass\").focus();\r\n");
      out.write("	      return false;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    if(phone == \"\") {\r\n");
      out.write("			alert(\"휴대폰번호를 입력해주세요.\");\r\n");
      out.write("			$(\"#phone\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	    // 휴대폰번호 정규표현식 처리\r\n");
      out.write("		let phone_pattern = /^\\d{3}-\\d{3,4}-\\d{4}$/;\r\n");
      out.write("	    if (!phone_pattern.test(phone)) {\r\n");
      out.write("	      alert(\"올바른 휴대폰번호가 아닙니다.\\n다시 입력해주세요.\");\r\n");
      out.write("	      $(\"#phone\").focus();\r\n");
      out.write("	      return false;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    if(email == \"\") {\r\n");
      out.write("			alert(\"이메일을 입력해주세요.\");\r\n");
      out.write("			$(\"#email\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	    // 이메일 정규표현식 처리\r\n");
      out.write("	    let email_pattern = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/;\r\n");
      out.write("	    if (!email_pattern.test(email)) {\r\n");
      out.write("	      alert(\"올바른 이메일 형식이 아닙니다.\\n다시 입력해주세요.\");\r\n");
      out.write("	      $(\"#email\").focus();\r\n");
      out.write("	      return false;\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    if(addr1 == \"\") {\r\n");
      out.write("			alert(\"주소를 입력해주세요.\");\r\n");
      out.write("			$(\"#addr1\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	    \r\n");
      out.write("	    if(addr2 == \"\") {\r\n");
      out.write("			alert(\"상세주소를 입력해주세요.\");\r\n");
      out.write("			$(\"#addr2\").focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// 회원가입 정보 입력값\r\n");
      out.write("		let datas = {\"userid\":userid,\"userpass\":userpass,\"name\":name,\"birth\":birth,\"phone\":phone,\"email\":email,\"addr1\":addr1,\"addr2\":addr2,\"mailchk\":mailchk,\"smschk\":smschk};\r\n");
      out.write("		\r\n");
      out.write("		// 회원가입 정보 입력값 전송\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			// 전송\r\n");
      out.write("			type  : \"POST\",\r\n");
      out.write("			url   	: \"/libJoinSave.do\",\r\n");
      out.write("			data 	: datas,\r\n");
      out.write("			// 결과값 세팅	\r\n");
      out.write("			datatype : \"text\",\r\n");
      out.write("			success 	 : function(data) {\r\n");
      out.write("				 if(data == \"1\") {\r\n");
      out.write("						alert(\"회원가입 완료\");\r\n");
      out.write("						location = \"/libLoginWrite.do\";\r\n");
      out.write("					 } else if(data == \"2\") {\r\n");
      out.write("						 alert(\"이미 사용중인 아이디입니다.\");\r\n");
      out.write("					 } else {\r\n");
      out.write("						 alert(\"가입 오류\");\r\n");
      out.write("					 }\r\n");
      out.write("				 },\r\n");
      out.write("			error 		 : 	function() {\r\n");
      out.write("				 alert(\"데이터 전송실패\");\r\n");
      out.write("			 }\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("// 입력한 아이디 중복체크 \r\n");
      out.write("function fn_userid(userid) {\r\n");
      out.write("	let result=\"\";\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		// 전송\r\n");
      out.write("		type  : \"POST\",\r\n");
      out.write("		url   	: \"/libUserIdCheck.do\",\r\n");
      out.write("		data 	: \"userid=\"+userid,\r\n");
      out.write("		async : false,\r\n");
      out.write("		// 결과값 세팅	\r\n");
      out.write("		datatype : \"text\",\r\n");
      out.write("		success 	 : function(data) {\r\n");
      out.write("				result = data;\r\n");
      out.write("			 },\r\n");
      out.write("		error 	: function() {\r\n");
      out.write("			alert(\"오류\");\r\n");
      out.write("			 return \"2\";\r\n");
      out.write("		 }\r\n");
      out.write("	});\r\n");
      out.write("	return result; \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  width: 800px;\r\n");
      out.write("  margin-left:300px;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("  width: 70px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  color: #333;\r\n");
      out.write("  appearance: none;\r\n");
      out.write("  -webkit-appearance: none;\r\n");
      out.write("  background-position: right 10px center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select:focus {\r\n");
      out.write("  border-color: #007bff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select[aria-invalid=\"true\"] {\r\n");
      out.write("  border-color: #ff0000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select::placeholder {\r\n");
      out.write("  color: #999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table1{\r\n");
      out.write("	width:100%;\r\n");
      out.write("	margin:0px auto;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	text-align:left;\r\n");
      out.write("	border-top:3px solid #cd8394;\r\n");
      out.write("	border-collapse:collapse;\r\n");
      out.write("}\r\n");
      out.write(".table1 th,\r\n");
      out.write(".table1 td {\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  border-bottom: 1px solid #ccc;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table1 th {\r\n");
      out.write("  background: #f1f1f1;\r\n");
      out.write("  color: #333;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table1 label.checkbox-label {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table1 label.checkbox-label input[type=\"checkbox\"] {\r\n");
      out.write("  margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_submit {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  background-color: #007bff;\r\n");
      out.write("  color: white;\r\n");
      out.write("  border: none;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("  font-size: 1em;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  transition: background-color 0.3s ease;\r\n");
      out.write("  margin-top:20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn_submit:hover {\r\n");
      out.write("  background-color: #0056b3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".frm_info {\r\n");
      out.write("  font-size: 0.9em;\r\n");
      out.write("  color: #999;\r\n");
      out.write("  margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write(".input {\r\n");
      out.write("  width: 150px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"header1\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@200&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function fn_logout() {\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type : \"POST\",\r\n");
      out.write("		data : \"\", //  전송되는 데이터 값은 없다.\r\n");
      out.write("		url : \"/libLogout.do\", \r\n");
      out.write("		\r\n");
      out.write("		datatype : \"text\",\r\n");
      out.write("		success 	 : function(data) {\r\n");
      out.write("			 if(data == \"1\") {\r\n");
      out.write("					alert(\"로그아웃 되었습니다.\");\r\n");
      out.write("					location = \"/\"; // 메인화면으로 이동\r\n");
      out.write("				 }\r\n");
      out.write("			 },\r\n");
      out.write("			error 		 : 	function() {\r\n");
      out.write("				 alert(\"전송실패\");\r\n");
      out.write("			 }\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"libtop\" >\r\n");
      out.write("<a href=\"/\">홈으로</a> | \r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div> ");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("    <header class=\"header2\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"libtitle\" >\r\n");
      out.write("<a href=\"/\">하이도서관</a>\r\n");
      out.write("&nbsp;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"searchFrm\" method=\"post\" action=\"/bookRent.do\" style=\"display: inline;\">\r\n");
      out.write("  <input type=\"hidden\" name=\"searchCondition\" id=\"searchCondition\" value=\"title\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"input-container\">\r\n");
      out.write("    <div class=\"icon-container\">\r\n");
      out.write("      <img src=\"../icon/inputsearch.gif\" class=\"input-icon\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <input type=\"text\" id=\"searchKeyword\" name=\"searchKeyword\" class=\"search\" onfocus=\"clearIcon()\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <input type=\"submit\" id=\"search\" name=\"search\" class=\"button\" style=\"position: relative; bottom: 9px;\" value=\"검색\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("	    <a href=\"/\"><img src=\"../icon/main.gif\" alt=\"search 아이콘\" class=\"mainicon\" style=\"vertical-align: middle;\"></a>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"nav\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  <table class=\"menu-btn\" style=\"width:1200px; align:center;\">\r\n");
      out.write("   		<colgroup>\r\n");
      out.write("			<col width=\"12%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"15%\"/>\r\n");
      out.write("			<col width=\"13%\"/>\r\n");
      out.write("		</colgroup>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td><a href=\"#\"></a></td>\r\n");
      out.write("      <td><a href=\"/guide.do\">이용안내</a></td>\r\n");
      out.write("      <td><a href=\"/bookSearch.do\">자료검색</a></td>\r\n");
      out.write("      <td><a href=\"/libNoticeList2.do\">도서관소식</a></td>\r\n");
      out.write("      <td><a href=\"/libReserve.do\">신청서비스</a></td>\r\n");
      out.write("      <td>\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </td>\r\n");
      out.write("      <td><a href=\"#\"></a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  <ul class=\"menu-list\">\r\n");
      out.write("   		<table width=\"1200px;\" style=\"font-size:20px;\">\r\n");
      out.write("	   		<colgroup>\r\n");
      out.write("				<col width=\"12%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"15%\"/>\r\n");
      out.write("				<col width=\"13%\"/>\r\n");
      out.write("			</colgroup>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/libMap.do\">오시는길</a></td>\r\n");
      out.write("				<td><a href=\"/bookSearch.do\">통합검색</a></td>\r\n");
      out.write("				<td><a href=\"/libNoticeList2.do\">공지사항</a></td>\r\n");
      out.write("				<td><a href=\"/libReserve.do\">열람실</a></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			    ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/guide.do\">이용시간</a></td>\r\n");
      out.write("				<td><a href=\"/bookRent.do\">대여하기</a></td>\r\n");
      out.write("				<td><a href=\"/libEventList2.do\">문화행사</a></td>\r\n");
      out.write("				\r\n");
      out.write("				<td><a href=\"/voluntary.do\">자원봉사신청</a></td>\r\n");
      out.write("				<td><a href=\"/libArchive.do?session_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${session_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">열람실기록</a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/reserveGuide.do\">열람실이용</a></td>\r\n");
      out.write("				<td><a href=\"/newBook.do\">신착도서</a></td>\r\n");
      out.write("				<td><a href=\"/libCalendar.do\">일정</a></td>\r\n");
      out.write("				<td><a href=\"/tourGuide.do\">도서견학신청</a></td>\r\n");
      out.write("				<td>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"/rentGuide.do\">대출/반납</a></td>\r\n");
      out.write("				<td><a href=\"/popularBook.do\">인기도서</a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("				<td><a href=\"#\"></a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("  </ul>");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section1\">\r\n");
      out.write("        <div class=\"sec1\">\r\n");
      out.write("            <aside class=\"aside\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("		<table style=\"border-collapse: collapse;width:220px;\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td style=\"font-size:35px;height:180px; background-size: cover;\">\r\n");
      out.write("				<a href=\"/libConditions.do\">회원가입</a>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"80\"><a href=\"/libLoginWrite.do\">로그인</a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"80\"><a href=\"/libFindUserId.do\">아이디찾기</a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"80\"><a href=\"/libFindUserPass.do\">비밀번호찾기</a></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td height=\"80\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>");
      out.write(" \r\n");
      out.write("            </aside>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"flex-item\">\r\n");
      out.write("                <div class=\"container\" style=\"border:0px solid black; margin-left:300px;\">\r\n");
      out.write("                    <!-- 본문 입력 -->\r\n");
      out.write("                    <div style=\"margin-bottom: 50px; font-size: 1.8em; font-weight: bold;\">\r\n");
      out.write("                        회원가입\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <form id=\"frm\" name=\"frm\">\r\n");
      out.write("                            <input type=\"hidden\" id=\"id_usable\" value=\"N\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <table class=\"table1\">\r\n");
      out.write("                                    <caption style=\"text-align:left; font-size: 1.2em;\">※회원정보입력</caption> \r\n");
      out.write("                                    <colgroup>\r\n");
      out.write("                                        <col width=\"15%\">\r\n");
      out.write("                                        <col width=\"*\">\r\n");
      out.write("                                    </colgroup>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th><label for=\"name\">이름</label></th>\r\n");
      out.write("                                            <td>\r\n");
      out.write("                                                <input type=\"text\" id=\"name\" name=\"name\" value=\"\" class=\"input\" size=\"10\">\r\n");
      out.write("                                            </td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("						                    <th><label for=\"userid\">아이디</label></th>\r\n");
      out.write("						                    <td>\r\n");
      out.write("						                    	<input type=\"text\" name=\"userid\" value=\"\" id=\"userid\" class=\"input \" minlength=\"4\" maxlength=\"12\">\r\n");
      out.write("						                        <span class=\"frm_info\"> ※ 영어/숫자 4~12자</span><br>\r\n");
      out.write("						                        <span id=\"msg_userid\"></span>\r\n");
      out.write("						                    </td>\r\n");
      out.write("						                </tr>\r\n");
      out.write("						                <tr>\r\n");
      out.write("						                    <th><label for=\"userpass\">비밀번호</label></th>\r\n");
      out.write("						                    <td>\r\n");
      out.write("						                    <input type=\"password\" name=\"userpass\" id=\"userpass\" class=\"input\" maxlength=\"20\">\r\n");
      out.write("						                    <span class=\"frm_info\">  ※ 영문대소문자, 숫자, 특수문자 중 3종류 이상으로 조합 6~20자리</span> \r\n");
      out.write("						                    </td>\r\n");
      out.write("						                </tr>\r\n");
      out.write("						                <tr>\r\n");
      out.write("						                    <th><label for=\"userpass2\">비밀번호 확인</label></th>\r\n");
      out.write("						                    <td>\r\n");
      out.write("						                    <input type=\"password\" name=\"userpass2\" id=\"userpass2\" class=\"input\" maxlength=\"20\">\r\n");
      out.write("						                    <span class=\"frm_info\"> ※ 비밀번호 확인을 위해 다시 한번 입력하세요</span>\r\n");
      out.write("						                    </td>\r\n");
      out.write("						                </tr>\r\n");
      out.write("						                <tr>\r\n");
      out.write("					                        <th><label for=\"birth\">생년월일</label></th>\r\n");
      out.write("					                        <td>\r\n");
      out.write("					                            <select id=\"y1\" name=\"y1\">\r\n");
      out.write("													");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("												</select>\r\n");
      out.write("												<span>년</span>\r\n");
      out.write("												<select id=\"m2\" name=\"m2\">	  \r\n");
      out.write("					                            	");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("												</select>\r\n");
      out.write("												<span>월</span>\r\n");
      out.write("												<select id=\"d3\" name=\"d3\">\r\n");
      out.write("					                            	");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("					                            </select>\r\n");
      out.write("					                            <span>일</span>\r\n");
      out.write("					                        </td>\r\n");
      out.write("					                    </tr>\r\n");
      out.write("					                    <tr>\r\n");
      out.write("					                        <th><label for=\"phone\">휴대폰번호</label></th>\r\n");
      out.write("					                        <td>\r\n");
      out.write("					                        	<div>\r\n");
      out.write("					                        	※ 휴대폰번호는 비밀번호 분실, 서비스 관련 메시지 전달 시 사용하므로 정확하게 입력하세요.<br>\r\n");
      out.write("												※ SMS수신에 체크하지 않을 경우 자료대출이나 반납, 도서예약 등의 서비스가 제한됩니다.<br>\r\n");
      out.write("					                        	</div>\r\n");
      out.write("					                            <select id=\"p1\" name=\"p1\">\r\n");
      out.write("					                            	<option value=\"\">선택</option>\r\n");
      out.write("																	\r\n");
      out.write("													<option value=\"010\" >010</option>\r\n");
      out.write("												\r\n");
      out.write("													<option value=\"011\" >011</option>\r\n");
      out.write("												\r\n");
      out.write("													<option value=\"016\" >016</option>\r\n");
      out.write("												\r\n");
      out.write("													<option value=\"017\" >017</option>\r\n");
      out.write("												\r\n");
      out.write("													<option value=\"018\" >018</option>\r\n");
      out.write("												\r\n");
      out.write("													<option value=\"019\" >019</option>\r\n");
      out.write("					                            </select>\r\n");
      out.write("					                            <span>-</span>\r\n");
      out.write("					                            <input type=\"text\" id=\"p2\" name=\"p2\" maxlength=\"4\" class=\"input\" style=\"width: 70px;\">\r\n");
      out.write("					                            <span>-</span>\r\n");
      out.write("					                            <input type=\"text\" id=\"p3\" name=\"p3\" maxlength=\"4\" class=\"input\" style=\"width: 70px;\">\r\n");
      out.write("					                            <label for=\"smschk\"><input type=\"checkbox\" name=\"smschk\" id=\"smschk\" value=\"Y\" checked>SMS를 받겠습니다.</label>\r\n");
      out.write("					                        </td>\r\n");
      out.write("					                    </tr>\r\n");
      out.write("					                    <tr>\r\n");
      out.write("					                        <th><label for=\"email\">E-mail</label></th>\r\n");
      out.write("					                        <td>\r\n");
      out.write("					                        	<div>※ 비밀번호 분실, 서비스 관련 메시지 전달 시 사용하므로 정확하게 입력하세요.</div>\r\n");
      out.write("					                            <input type=\"email\" name=\"email\" value=\"\" id=\"email\" class=\"input\" style=\"width:350px;\" size=\"70\" maxlength=\"100\"><br>\r\n");
      out.write("					                            <label for=\"mailchk\"><input type=\"checkbox\" name=\"mailchk\" id=\"mailchk\" value=\"Y\" checked>정보 메일을 받겠습니다.</label>\r\n");
      out.write("					                        </td>\r\n");
      out.write("					                    </tr>\r\n");
      out.write("				                       <tr>\r\n");
      out.write("								            <th>주소</th>\r\n");
      out.write("								            <td><input type=\"text\" id=\"addr1\" name=\"addr1\" class=\"input\" style=\"width:350px;\" readonly /></td>\r\n");
      out.write("								        </tr>\r\n");
      out.write("								        <tr>\r\n");
      out.write("								            <th>상세 주소</th>\r\n");
      out.write("								            <td><input type=\"text\" id=\"addr2\" name=\"addr2\" class=\"input\" style=\"width:350px;\" /></td>\r\n");
      out.write("								        </tr>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"submit\">\r\n");
      out.write("                                <input type=\"submit\" value=\"회원가입\" id=\"btn_submit\" onclick=\"return false;\" class=\"btn_submit\" accesskey=\"s\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 본문 입력 -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("남양주시평생학습원사업자번호 : 132-83-05566대표자 : 이순덕<br>\r\n");
      out.write("주소 : 경기도 남양주시 다산중앙로82번안길 138(다산동 정약용도서관)<br>\r\n");
      out.write("진건도서관경기도 남양주시 진건읍 진건오남로 41-25TEL : 031-590-8260<br>\r\n");
      out.write("Copyright © 남양주시평생학습원. ALL RIGHTS RESERVED.<br>");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    <aside class=\"new-aside\">\r\n");
      out.write("        NEW-ASIDE<br>\r\n");
      out.write("        NEW-ASIDE\r\n");
      out.write("    </aside>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /member/../include/header1.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("s_userid");
      // /member/../include/header1.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/member/../include/header1.jsp(5,0) '${sessionScope.SessionUserID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionUserID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /member/../include/header1.jsp(37,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<a href=\"/libConditions.do\">회원가입</a> |\r\n");
          out.write("	<a href=\"/libLoginWrite.do\"><b>로그인</b></a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /member/../include/header1.jsp(41,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != null && s_userid != 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<a href=\"/libMemberDetail.do\">내 정보</a> |\r\n");
          out.write("	<a href=\"javascript:fn_logout()\"><b>로그아웃</b></a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /member/../include/header1.jsp(45,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<a href=\"/adminMain.do\" style=\"color: red; font-weight: bold;\">관리자모드</a> |\r\n");
          out.write("	<a href=\"javascript:fn_logout()\"><b>로그아웃</b></a>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /member/../include/nav.jsp(4,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("session_id");
      // /member/../include/nav.jsp(4,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/member/../include/nav.jsp(4,4) '${sessionScope.SessionUserID }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.SessionUserID }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /member/../include/nav.jsp(24,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      	<a href=\"/libLoginWrite.do\">나의 도서관</a> \r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /member/../include/nav.jsp(27,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      	<a href=\"/myBookList.do\">나의 도서관</a> \r\n");
          out.write("      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /member/../include/nav.jsp(52,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			    	<a href=\"/libLoginWrite.do\">대여목록</a> \r\n");
          out.write("			    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /member/../include/nav.jsp(55,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			    	<a href=\"/myBookList.do\">대여목록</a> \r\n");
          out.write("			    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /member/../include/nav.jsp(78,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s_userid != 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                	<a href=\"/libMemberDetail.do\">내 정보</a>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /member/libJoinWrite.jsp(388,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /member/libJoinWrite.jsp(388,13) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(1950);
      // /member/libJoinWrite.jsp(388,13) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(2023);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("														<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            if (_jspx_meth_c_005fif_005f8(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("													");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /member/libJoinWrite.jsp(389,35) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i==2000 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("selected");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /member/libJoinWrite.jsp(394,34) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("i");
      // /member/libJoinWrite.jsp(394,34) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1);
      // /member/libJoinWrite.jsp(394,34) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(12);
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("														<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("													");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /member/libJoinWrite.jsp(400,34) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("i");
      // /member/libJoinWrite.jsp(400,34) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setBegin(1);
      // /member/libJoinWrite.jsp(400,34) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setEnd(31);
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("														<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("													");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }
}
